name: Deploy

on: [push]

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Installs serverless CLI
        run: npm install serverless -g
      - name: Install Node Dependencies 
        run: npm install
      # https://stackoverflow.com/questions/51678005/serverless-service-files-not-changed-skipping-deployment/53223427#53223427
      - run: serverless deploy --force
        working-directory: ./game-room-service
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
